ezerssss/segunda

app/index.tsx, firebase/auth.ts, firebase/functions.ts, firebase/index.ts, hooks/useLogin.tsx
#3 
Connect firebase functions backend to the app via SDK
=> [Misc][Ezra] connect firebase functions

constants/post.ts, enums/bid.ts, enums/campus.ts, enums/post.ts, types/bidder.ts, types/chat.ts, types/item.ts, types/post.ts, types/response.ts, types/user.ts
Follow schemas from backend source of truth
=> [Misc][Ezra] copy schema from backend source of truth

enums/collection.ts, types/user.ts
=> [Misc][Ezra] added setup user schema

app/index.tsx, firebase/functions.ts
Update firebase functions reference
=> [Adjustment][Ezra] Update Functions

types/post.ts
=> [Hotfix][Ezra] add likes to post schema

README.md
Update readme to be more useful
=> [Chore][Ezra] Update Readme

app/seller/item-form.tsx, app/seller/seller-form.tsx, types/item.ts
Remove image state to simplify
=> [Adjustment][Ezra] even better image handling

app/seller/seller-form.tsx
useWatch to trigger vdom update
=> [Fix][Ezra] useWatch to trigger vdom update

app/seller/form.tsx, app/user-setup/index.tsx, contexts/userContext.ts
Fixed "source.uri should not be empty string" by
- adding UserDataType to UserContext user
- Get user details from firebase document 
- changed from
- photoUrl to imageUrl
- displayName to name
=> [Fix][Olana] source.uri should not be empty string

app/_layout.tsx, contexts/userContext.ts
=> [Fix][Ezra] Fix User Context Data

types/bidder.ts, types/chat.ts, types/item.ts, types/post.ts, types/user.ts
Change schema for the nth time
=> [Adjustment][Ezra] Change schema vntimes

types/bidder.ts
=> [Adjustment][Ezra] bidder schema change

firebase/functions.ts, types/bidder.ts
#30 
Add firebase function and schemas
=> [Adjustment][Ezra] add firebase function, and schema

components/browse-posts/post-images.tsx, types/item.ts
=> [Adjustment][Ezra] copy schema and index fix

app/browse-posts/index.tsx, hooks/useGetPosts.tsx
=> [Fix][Ezra] snapshot listener and fetch more posts

firebase/functions.ts, types/bidder.ts, types/chat.ts
Add types and function definitions
=> [Adjustment][Ezra] Chat schema change

app/(protected)/(tabs)/home.tsx, app/(protected)/view-post/[postId].tsx, app/(protected)/view-post/_layout.tsx, components/browse-posts/post-item.tsx, components/skeletons/browse-post.tsx, components/skeletons/post-header.tsx, components/skeletons/view-post.tsx
- Added loading states through Skeletons and Text
https://github.com/user-attachments/assets/614278e5-57d8-42f8-ab0d-159dd4b5f61d
=> [Enhancement][Olana] Better Loading State through Skeletons and Text

app/(protected)/(tabs)/home.tsx, components/browse-posts/post-item.tsx
=> [Adjustment][Ezra] Every post in browse-post has divider

firebase/functions.ts, types/post.ts
deletePost Firebase Function types and definition
=> [Adjustment][Ezra] new schema for delete and function definition

firebase/db.ts
=> [Adjustment][Ezra] default db

firebase/functions.ts, types/item.ts
=> [Definition][Ezra] delete item type and function def

firebase/functions.ts, types/item.ts
=> [Def][Ezra] edit types and function definition

constants/collections.ts, enums/collection.ts, firebase/functions.ts, types/notification.ts
Notification types and function definitions
=> [Def][Ezra] notification definitiions of types and functions

types/user.ts
=> [Definition] Updated UserDataSchema to include isSetup boolean property

app/(protected)/(tabs)/home.tsx, app/(protected)/post-form.tsx, components/seller-form-bar.tsx
Added an input bar just like in FB to navigate to seller form page
=> [Frontend][AJ] Seller form route in homepage

app/(protected)/(tabs)/_layout.tsx, app/(protected)/_layout.tsx, app/(protected)/chat/(tabs)/_layout.tsx, app/(protected)/chat/[chatId].tsx, app/(protected)/post-form.tsx, app/(protected)/view-post/[postId].tsx, components/browse-posts/post-item.tsx, components/chat/list.tsx, components/chat/message.tsx, components/chat/new-message.tsx, components/chat/thumbnail.tsx, components/post-header.tsx, components/seller-form-bar.tsx, components/user/user-header.tsx, components/view-post/item-card.tsx, custom-theme.json, hooks/useGetChatNotif.tsx, package-lock.json, package.json, states/chat.ts, types/chat.ts, utils/date.ts
- UI of chat list and messages list
- Minor changes to other UI components
=> [UI][Ezra] Messages list

eas.json
=> [Misc][Ezra] APK Config

app/(protected)/(tabs)/catalogue.tsx, app/(protected)/search-items.tsx, types/item.ts
=> [Adjustment][Ezra] add isSold attribute in item

components/view-post/full-screen-item-card.tsx
polish for peso sign in viewing full item
=> [Rian][Polish] peso sign polish for viewing full item
